package xyz.candycrawler.wizardstataggregator.infrastructure.db.entity

internal data class CardLimitedStatsRecord(
    val id: Long?,
    val name: String,
    val mtgaId: Int,
    val matchType: String,
    val color: String,
    val rarity: String,
    val url: String,
    val urlBack: String,
    val types: List<String>,
    val layout: String,
    val seenCount: Int,
    val avgSeen: Double?,
    val pickCount: Int,
    val avgPick: Double?,
    val gameCount: Int,
    val poolCount: Int,
    val playRate: Double,
    val winRate: Double,
    val openingHandGameCount: Int,
    val openingHandWinRate: Double,
    val drawnGameCount: Int,
    val drawnWinRate: Double,
    val everDrawnGameCount: Int,
    val everDrawnWinRate: Double,
    val neverDrawnGameCount: Int,
    val neverDrawnWinRate: Double,
    val drawnImprovementWinRate: Double,
)
